### ISSUE TITLE
QRコードの読み取りについて

### ISSUE THREAD

**Issue by tapi-y** [OneNightROBOCON/onigiri_war#19]
QRコードの読み取り率が低い
・RealsenseR200とUSBカメラでの認識率にあまり差がない
・移動中では認識できないため、フィールド上の特点しか取れないと思われる

**Comment by dashimaki360** [comment]
ブレに関してはシャッタースピードの変更で対応

読み取り率はマーカーをQRコードからARマーカーに変更して対応
