### ISSUE TITLE
ONIGIRIBOT 搭載センサの決定

### ISSUE THREAD

**Issue by dashimaki360** [OneNightROBOCON/onigiri_war#3]

**Comment by tapi-y** [comment]
カメラ：realsense r200(付属)  realsenseROSパッケージ導入済
Lidar ：日立LG　Lidar(付属)　laserパッケージ導入済
要確認
・カメラ及びLidarのTFの確認が必要
・カメラの位置固定方法の検討

**Comment by tapi-y** [comment]
障害物センサ：
・左右斜め前方赤外線測距センサ 2個
・前方バンパースイッチ　2個
　上記による緊急停止モードへの移行の解除が必要

**Comment by dashimaki360** [comment]
緊急停止モードへの移行の解除ってやった経験ある？
