### ISSUE TITLE
ros_simulatorのcatkin_makeでエラー その１

### ISSUE THREAD

**Issue by yupos0221** [OneNightROBOCON/onigiri_war#40]
ros_simulatorのcatkin_makeでエラー出ます。

はじめにdriver_baseのパッケージがないと言われたので、
次のコマンドでros_driverを入れました
`git clone https://github.com/ros-drivers/driver_common.git`

これでdriver_baseのエラーは回避できましたが、
解決策としてこれは正しいでしょうか？

以下エラー内容

##############################################################################
-- +++ processing catkin package: 'rulo_simulation'
-- ==> add_subdirectory(ros_simulator)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "driver_base" with
  any of the following names:

    driver_baseConfig.cmake
    driver_base-config.cmake

  Add the installation prefix of "driver_base" to CMAKE_PREFIX_PATH or set
  "driver_base_DIR" to a directory containing one of the above files.  If
  "driver_base" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  ros_simulator/CMakeLists.txt:4 (find_package)

-- Could not find the required component 'driver_base'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "driver_base" with
  any of the following names:

    driver_baseConfig.cmake
    driver_base-config.cmake

  Add the installation prefix of "driver_base" to CMAKE_PREFIX_PATH or set
  "driver_base_DIR" to a directory containing one of the above files.  If
  "driver_base" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  ros_simulator/CMakeLists.txt:4 (find_package)
##############################################################################

**Comment by dashimaki360** [comment]
@yupos0221 これってもうクローズして大丈夫?

**Comment by yupos0221** [comment]
@dashimaki360 
ros_simulatorをkinetic版にすることで解決しました
ありがとうございました。
