### ISSUE TITLE
ros_simulatorのcatkin_makeでエラー その２

### ISSUE THREAD

**Issue by yupos0221** [OneNightROBOCON/onigiri_war#41]
ros_simulatorのcatkin_makeでエラーです。その２

[driver_baseのエラー](https://github.com/OneNightROBOCON/onigiri_war/issues/40)を回避した後、
エラーがgazebo_ros_elevatorが無いという内容に変化

gazeboのプラグインが足りないというエラーだと思うのですが解決策が分かりません。
何か知っていたら教えてください。

gazebo自体がインストールされているのは確認済みです。（Versionは７．０）

#################################################################################
CMake Error at /opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake:323 (_install):
  install TARGETS given target "gazebo_ros_elevator" which does not exist in
  this directory.
Call Stack (most recent call first):
  ros_simulator/CMakeLists.txt:254 (install)

-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
#################################################################################

**Comment by dashimaki360** [comment]
たぶん
ros_simulator がindigo用の古いバージョンだったのでは？

ros_simulator をkinetic versionではエラー出ませんでした

kinetic verのros_simulatorの配布場所はだれか補足希望

**Comment by dashimaki360** [comment]
@yupos0221
 これってもうクローズして大丈夫?

**Comment by yupos0221** [comment]
@dashimaki360 
大丈夫です！
ros_simulatorをkineticにすることで解決しました
ありがとうございました。
