### ISSUE TITLE
要望

### ISSUE THREAD

**Issue by yukiimai** [OneNightROBOCON/onigiri_war#50]
・Wikiに書かれているQ&Aが前回（第３回）の内容ですので、一旦消しておくのが良いと思います。
contribute権限いただければ対応します。

・　gitignoreに.urdfを追加しておいた方が良いかと思います。

**Comment by dashimaki360** [comment]
ご指摘ありがとうございます!!

ご協力いただけるということで,OneNightROBOCON アカウントにメンバーとして招待しました.
wikiの更新していただけると大変たすかります....


>・　gitignoreに.urdfを追加しておいた方が良いかと思います。
ロボットモデルのアップロードを防止するためにも良さそうな対策だと思います.
対応します.

**Comment by yukiimai** [comment]
了解しました。Facebookで出た内容を絡めていきます。
